### PR TITLE
Upgrade github actions versions to latest

### PR DESCRIPTION
**Pull request by shahar-h**
image

### CODE REVIEW

**Comment by shahar-h** [comment]
@another-rex can you take a look?

**Review by another-rex — APPROVED** [review]
Thanks!

**Comment by another-rex** [comment]
I'll set up renovatebot to automate this in the future.

**Comment by shahar-h** [comment]
@another-rex can this be merged?

**Comment by another-rex** [comment]
Just waiting to see what renovatebot would do to check the configuration. Will be merged soon.

**Comment by another-rex** [comment]
A new release will be made next week!

**Pull request merged**
