### PR TITLE
Fix configuration not found warning when using unified gh workflow

### LINKED ISSUE #7: configuration not found warning when using unified gh workflow
I'm using the unified osv-scanner gh workflow in my repo:

```yaml
name: OSV-Scanner

on:
  pull_request:
    branches:
    - "main"
  merge_group:
    branches:
    - "main"
  push:
    branches:
    - "main"
  schedule:
  - cron: '44 15 * * 5'

permissions:
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78"  # v1.7.1
    permissions:
      contents: read
      # Require writing security events to upload SARIF file to security tab
      security-events: write
  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78"  # v1.7.1
    permissions:
      contents: read
      # Require writing security events to upload SARIF file to security tab
      security-events: write
```

I get the following warning on PRs:
image

I guess that it's related to the fact that the job name is different between reusable workflows:
* [osv-scanner-reusable.yml](https://github.com/google/osv-scanner-action/blob/main/.github/workflows/osv-scanner-reusable.yml) - `osv-scan`
* [osv-scanner-reusable-pr.yml](https://github.com/google/osv-scanner-action/blob/main/.github/workflows/osv-scanner-reusable-pr.yml) - `scan-pr`

Can you assist?

### PR DESCRIPTION
**Pull request by shahar-h**
Fixes #7 
See https://github.com/google/osv-scanner-action/issues/7#issuecomment-2088054836

### CODE REVIEW

**Comment by oliverchang** [comment]
Thank you very much for the contribution! I'll defer this to @another-rex , who is still out until next week.

**Comment by another-rex** [comment]
I did test this change multiple different times in my own repo (https://github.com/another-rex/staging-osv-scanner-action/tree/fix-workflow-naming), and pointed another repo at it, but PRs still shows the error for some reason (https://github.com/another-rex/oss-fuzz-gen/pull/2/checks?check_run_id=24492679877). 

I think it originates from the scheduled scan being skipped, which changing the name won't fix, but I'm not sure about this.

**Comment by shahar-h** [comment]
Tested again on my repo and it works:
https://github.com/shahar-h/gateway/pull/19
https://github.com/shahar-h/gateway/pull/19/checks?check_run_id=25260222254

I noticed that your both PR branches are not rebased against main branch. Can you try to rebase them or open a new PR?

**Review by another-rex — APPROVED** [review]
Still can't replicate this, but is a small change so let's merge it and see if it works :)

**Pull request merged**
